apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: bp57qfu3i-nodejs 
  janus-idp.io/tekton: bp57qfu3i-nodejs
  backstage.io/kubernetes-id: bp57qfu3i-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bp57qfu3i-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml