apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bp57qfu3i-nodejs
  janus-idp.io/tekton: bp57qfu3i-nodejs
  backstage.io/kubernetes-id: bp57qfu3i-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bp57qfu3i-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
